import os
import json
import numpy as np
from rknn.api import RKNN

ONNX_MODEL = './gemma-e2b-vision.onnx'
RKNN_MODEL = './gemma-e2b-vision.rknn'
DATASET_PATH = None
RKNN_LOAD_JSON = 'gemma4_vision_rknn_load.json'


def _resolve_path(path, base_dir):
    if path is None:
        return None
    if os.path.isabs(path):
        return path
    return os.path.abspath(os.path.join(base_dir, path))

def _load_rknn_load_cfg(json_path):
    json_path = os.path.abspath(json_path)
    with open(json_path, 'r', encoding='utf-8') as f:
        cfg = json.load(f)
    return cfg, os.path.dirname(json_path)


def _load_initial_values(initial_cfg, base_dir):
    """把 json 里的 input_initial_val 描述恢复成 rknn.load_onnx 可用的列表。"""
    ret = []
    for item in initial_cfg:
        if item is None:
            ret.append(None)
        elif isinstance(item, dict) and item.get('type') == 'npy':
            ret.append(np.load(_resolve_path(item['path'], base_dir)))
        elif isinstance(item, str):
            # 兼容简单写法: [null, "gemma4_pos_ids_384x384.npy"]
            ret.append(np.load(_resolve_path(item, base_dir)))
        else:
            raise ValueError(f'Unsupported input_initial_val item in json: {item}')
    return ret


if __name__ == '__main__':

    from argparse import ArgumentParser
    parser = ArgumentParser(description="Export FastVLM vision to RKNN model") 
    parser.add_argument("--onnx_path", type=str, help="onnx model path", required=False, default=ONNX_MODEL)
    parser.add_argument("--rknn_path", type=str, help="output rknn model path", required=False, default=RKNN_MODEL)
    parser.add_argument('--platform', type=str, default= "rk1820", help='Target platform (e.g. rk1820)')
    parser.add_argument("--dataset_path", type=str, help="model quantization dataset path", required=False, default=DATASET_PATH)
    parser.add_argument('--core_num', type=int, default=8, help='core_num (1-8)')
    parser.add_argument('--rknn_load_json', type=str, required=False, default=RKNN_LOAD_JSON,
                        help='RKNN load_onnx json generated by export_vision.py')
    args = parser.parse_args()

    cfg, json_base_dir = _load_rknn_load_cfg(args.rknn_load_json)
    load_onnx_cfg = cfg['load_onnx']

    input_initial_val = _load_initial_values(load_onnx_cfg.get('input_initial_val', []), json_base_dir)

    # Create RKNN object
    rknn = RKNN(verbose=True)

    # pre-process config
    print('--> config model')
    rknn.config(target_platform=args.platform, 
                core_num=args.core_num, 
                quantized_dtype='w4a16', quantized_algorithm='normal', quantized_method='group32',
                mean_values=[[0,0,0]],
                std_values=[[255,255,255]],
                input_attrs={'pixel': {'dtype': 'uint8', 'layout': 'NHWC'}},
                )
    print('done')

    # Load model
    print('--> Loading model')
    ret = rknn.load_onnx(model=args.onnx_path,
                         inputs=load_onnx_cfg['inputs'],
                         input_size_list=load_onnx_cfg['input_size_list'],
                         input_initial_val=input_initial_val)
    if ret != 0:
        print('Load model failed!')
        exit(ret)
    print('done')

    # Build model
    print('--> Building model')
    ret = rknn.build(do_quantization=True, dataset=args.dataset_path)
    if ret != 0:
        print('Build model failed!')
        exit(ret)
    print('done')

    # Export rknn model
    print('--> Export RKNN model')
    ret = rknn.export_rknn(args.rknn_path)
    if ret != 0:
        print('Export rknn failed!')
        exit(ret)
    print('done')
    
    rknn.release()